create table category (id int8 generated by default as identity, nome varchar(255), primary key (id));
create table products (id int8 generated by default as identity, author varchar(255), description varchar(255), image varchar(255), price float8, publishing_company varchar(255), title varchar(255), category_id int8, primary key (id));
alter table if exists products add constraint FK1cf90etcu98x1e6n9aks3tel3 foreign key (category_id) references category;
